spring:
  application:
    name: otclients
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
#App info
app:
  name: @project.name@
  version: @project.version@

server:
  port: ${PORT:8080}
  tomcat:
    max-http-form-post-size: 10MB